apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  type: ClusterIP
  ports:
  - name: nginx-ex-port
    port: 9113
    protocol: TCP
    targetPort: 9113
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
