apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: docker.io/vii98/nginx-status:latest # Образ из которого создается контейнер
          livenessProbe:
            tcpSocket: { port: 8000 }
          imagePullPolicy: Always
        - name: nginx-exporter
          image: docker.io/nginx/nginx-prometheus-exporter:latest
          ports:
            - name: nginx-ex-port
              containerPort: 9113
          args:
            - -nginx.scrape-uri=http://localhost:8000/basic_status
