apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: {{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.port }}
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.port }}
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.port }}
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
      volumes:
      - name: redis-data
        emptyDir: {}

