apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hipster-shop
namePrefix: prod-
commonLabels:
  environment: hipster-shop-prod

images:
- name: gcr.io/google-samples/microservices-demo/recommendationservice
  newTag: v0.1.3
  
bases:
- ../../base
