apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  accessKey: bWluaW8K
  secretKey: bWluaW8xMjMK
---
#- name: MINIO_ACCESS_KEY
#  value: "minio"
#- name: MINIO_SECRET_KEY
#  value: "minio123"

  
