apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  accessKey: minio
  secretKey: minio123
---
#- name: MINIO_ACCESS_KEY
#  value: "minio"
#- name: MINIO_SECRET_KEY
#  value: "minio123"

  
