apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  accessKey: bWluaW8=
  secretKey: bWluaW8xMjM=
---
#- name: MINIO_ACCESS_KEY
#  value: "minio"
#- name: MINIO_SECRET_KEY
#  value: "minio123"

  
