apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hipster-shop-dev
namePrefix: dev-
commonLabels:
  environment: hipster-shop-dev

images:
- name: gcr.io/google-samples/microservices-demo/recommendationservice
  newTag: latest
  
bases:
- ../../base
